# INTENCIONALMENTE VULNERÁVEL PARA O LAB
FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json ./

# Executando como root (Má prática)
# Utilizando versão muito antiga do node que possui CVEs conhecidas
RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "start"]
